### ISSUE TITLE
Developer tool console errors

### ISSUE THREAD

**Issue by pabl0xf** [Diegolmi/Vet-puercoArania#44]
![image](https://user-images.githubusercontent.com/6700982/89738179-9109aa00-da2b-11ea-98b0-b48c91578100.png)
![image](https://user-images.githubusercontent.com/6700982/89738200-b5fe1d00-da2b-11ea-83c3-db4b0a45ff77.png)

Hay muchos errores y warnings desde el landing page por defecto, antes de comenzar a utlizar la Web

**Comment by Diegolmi** [comment]
Corregidos los errores.
