### ISSUE TITLE
Validaciones form registro

### ISSUE THREAD

**Issue by pabl0xf** [Diegolmi/Vet-puercoArania#45]
![image](https://user-images.githubusercontent.com/6700982/89738293-3de42700-da2c-11ea-87e1-a4f6ccdb063b.png)
Parecen faltar validaciones en campo de registro
![image](https://user-images.githubusercontent.com/6700982/89738300-4ccad980-da2c-11ea-8821-c03441a53e7e.png)

Este usurio pudo registrarse pero no es posible realizar login, si bien obtuve la pantalla de confirmacion. 

- Es posible escribir una contraseña distinta en el campo confirmar contraseña, el frontend no informa de los errores

**Comment by Diegolmi** [comment]
Listo todas las validaciones.
