### ISSUE TITLE
File Names

### ISSUE THREAD

**Issue by fabriziotonin** [Diegolmi/Vet-puercoArania#47]
Los nombres de los archivos, deberían tener el nombre de los componentes y también se debería elegir entre archivos js o jsx

- Evitar usar style.css y usar nombre del componente css

- Evitar usar el nombre de index.js y usar nombre del componente js

![image](https://user-images.githubusercontent.com/51201108/91885778-b53d5d00-ec5e-11ea-8f4a-a30c73f4b757.png)

**Comment by Diegolmi** [comment]
Corregido
