### ISSUE TITLE
Merge Conflicts

### ISSUE THREAD

**Issue by fabriziotonin** [Diegolmi/Vet-puercoArania#48]
En los componentes de Alimentos.js, CardAlimentos.js, Farmacia Component, Galería Component, SeccionTiendEC Component, Sidebar-E-commerce style.css, stepper Component
![image](https://user-images.githubusercontent.com/51201108/91885687-95a63480-ec5e-11ea-86e4-cd0d513861a7.png)

Estos componentes y sus archivos js y algunos de ellos el css tienen conflictos de merge que están imposibilitando la ejecución correcta de la pagina

**Comment by Diegolmi** [comment]
Corregido
