### ISSUE TITLE
Logeo de usuario

### ISSUE THREAD

**Issue by fabriziotonin** [Diegolmi/Vet-puercoArania#50]
Despues de logear un usuario no avisa si se logeo correctamente tampoco me redirige queda en la ventana de logeo

**Comment by Diegolmi** [comment]
Hola Fabrizio. No encuentro el error aqui. Porque yo si puedo loguearme correctamente y me lleva  a la seccion que corresponde.

**Comment by Diegolmi** [comment]
Listo el alert que avisa que el logueo fue exitoso

**Comment by fabriziotonin** [comment]
Cuando logeo sigue sin avisar del logeo ni me redirige, al hacer click en registrarse despues de tratar logear me redirige a la pantalla principal logeado 
![image](https://user-images.githubusercontent.com/51201108/98405933-d601a480-204b-11eb-97d6-d803fc1b6265.png)
Despues voy a registrarme y me redirige logeado
![image](https://user-images.githubusercontent.com/51201108/98405967-e580ed80-204b-11eb-85f8-a745c066fa47.png)

**Comment by fabriziotonin** [comment]
El Issue persiste que aunque coloque los datos me dice que estan incorrectos pero al regresar a la pagina principal si estoy logeado
![image](https://user-images.githubusercontent.com/51201108/103033229-c6c5b000-4540-11eb-9b72-c68071e9b9c8.png)
Y ahora salgo como logeado
![image](https://user-images.githubusercontent.com/51201108/103033256-d218db80-4540-11eb-9f97-6e456ed260ee.png)

**Comment by martincho111986** [comment]
issue resuelto
