### ISSUE TITLE
Add a Mascot on "Perfil" do not render properly 

### ISSUE THREAD

**Issue by fabriziotonin** [Diegolmi/Vet-puercoArania#55]
![image](https://user-images.githubusercontent.com/51201108/94841647-b7771080-03f0-11eb-9742-7b678146ca61.png)
Ahi ya agregue una mascota pero no me renderiza la mascota hasta que cambio de componente o actualizo la pagina

**Comment by martincho111986** [comment]
fue resuelto este inconveniente tambien
