### ISSUE TITLE
Registro usuario no me permite espacios en nombre

### ISSUE THREAD

**Issue by fabriziotonin** [Diegolmi/Vet-puercoArania#58]
Cuando trato de colocar mis dos nombres no me deja colocar espacios
![image](https://user-images.githubusercontent.com/51201108/98407264-21b54d80-204e-11eb-8a71-e398c7292cfb.png)

**Comment by martincho111986** [comment]
Ese error a mi no me sale, estoy verificando la validacion del form, y no hay ningun error

![Screenshot_2020-12-12 Veterinaria Puerco Araña](https://user-images.githubusercontent.com/57008725/101973717-c5c78100-3c18-11eb-93e1-c02c783e7ede.png)

**Comment by fabriziotonin** [comment]
Los Issues con el registro persisten los espacios me los toma como signos
![image](https://user-images.githubusercontent.com/51201108/103033152-9251f400-4540-11eb-88e7-cda5b2b25973.png)

**Comment by martincho111986** [comment]
ya esta resuelto este issue, me olvide de hacer el merge
